imagecrop/config/routes.rb
Rails.application.routes.draw do

  resources :images, only: [:new, :create]

end

imagecrop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

imagecrop/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
  end

  def create
    convert_file(params[:source])
    redirect_to "/#{cropped_file_name}"
  end

  private

  def public_directory_for(name)
    Rails.root.join("public", name)
  end

  def convert_file(file)
    system("convert #{file.path} -resize '#{height}x#{width}^' -gravity center -crop '#{height}x#{width}+0+0' #{public_directory_for(cropped_file_name)}")
  end

  def cropped_file_name
    [params[:name], "cropped", file.original_filename].compact.join("-").downcase
  end

  def file
    params[:source]
  end

  def height
    params[:height].presence || "70"
  end

  def width
    params[:width].presence || "70"
  end
end

imagecrop/app/helpers/application_helper.rb
module ApplicationHelper
end

imagecrop/app/helpers/images_helper.rb
module ImagesHelper
end

imagecrop/app/views/images/new.html.erb
<h1>Croppy</h1>
<p>Let's do this...</p>

<div class="uploader">
  <%= form_tag images_path, multipart: true do %>
    <div class="row">
      <label for="name">Name</label>
      <%= text_field_tag :name %>
    </div>
    <div class="row">
      <label for="name">Height</label>
      <%= text_field_tag :height %>
    </div>
    <div class="row">
      <label for="name">Width</label>
      <%= text_field_tag :width %>
    </div>
    <div class="row">
      <label for="source">Source Image</label>
      <%= file_field_tag :source %>
    </div>
    <div class="row">
      <input id="submit-button" type="submit" name="Commit" />
    </div>
  <% end %>
</div>

imagecrop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imagecrop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>